package:
  name: pypgx
  version: "0.1.37"

source:
  url: https://files.pythonhosted.org/packages/09/99/13a91fafc9547d4c8a52dfd52051b8eae634abc8b6ef9e1cdab28d67b4fb/pypgx-0.1.37.tar.gz
  sha256: c40cbf077c923af8a9541444c45ea185c6154e82f295e784554c231ed8b48e56

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pypgx

about:
  home: https://pypgx.readthedocs.io/en/latest/?badge=latest
