package:
  name: pypgx
  version: "0.2.0"

source:
  git_url: https://github.com/sbslee/pypgx.git
  git_rev: 0.2.0
  git_depth: 1

requirements:
  build:
    - python
    - setuptools
    - python
    - bs4
    - lxml
    - pandas
    - pysam
    - requests

  run:
    - python
    - bs4
    - lxml
    - pandas
    - pysam
    - requests

test:
  imports:
    - pypgx

about:
  home: https://pypgx.readthedocs.io/en/latest/?badge=latest
