package:
  name: pypgx
  version: "0.2.0"

source:
  git_url: https://github.com/sbslee/pypgx.git
  git_depth: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bs4
    - lxml
    - pandas
    - pysam
    - requests
    - scipy
    - matplotlib
    - gatk4=4.1.9.0
    - java-jdk=8.0.112

test:
  imports:
    - pypgx

about:
  home: https://pypgx.readthedocs.io/en/latest/?badge=latest
